kind: ENC[AES256_GCM,data:MVF1/w1x,iv:GzRZSLbRxI2k2JfIeaegN7WLh4D/6pnhgVMAqMHACxM=,tag:icSLYp/WOyBvveZjDbBjCw==,type:str]
ansible_user: ENC[AES256_GCM,data:OQCyRQ==,iv:+ua/ADlrrmho0wR4rCKFt0/UA06yjBVB+g1vRgyB32k=,tag:M+MHW4paTUS9uOy3pQPOjA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cFK+h9qsha+S,iv:Wa8eU1ZDG+V9/G4OOUYLjdatMoD9y9Uncv1uLgNP+4g=,tag:QXVic0zlZKm4cRbBI2qITg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12npq05s3sct6q03znt84ppgdgpd7nwagsfkdvdxlu5e5dq5jn35smw5g3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERk5WellFV25YaERBTFln
            K29ieVVaUGZBTldFNFBxeGR6NmZvNVdZZ1MwClRRWW1WeDZMQ1RTUVBZMWt2T2tq
            cGdrNmtQcmI4bHNvbUl3NjJtUlgxOU0KLS0tIFFlbTduUlo5bEp0THFvckgrQmxa
            bXlWSXhVTEhROFE1b3BKUVNPQU1oVnMKw6/8RbzB+hUhPs0co0/KJjxkr44rmtfQ
            OIvzuQsNuCbL3kIHOZKvlfwreo2TtkN476/kyoi6zBdS42Ee4cATDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T09:37:55Z"
    mac: ENC[AES256_GCM,data:vrhHnqI76n68YFMWpGgHwz9BIJd0BRRSLwpf5m2fFi4THvHUh9Xp3fpx4dQHDenvCUnNvgAjGOb2bSzwjpI2i5KJOASL1SCRdB7Fd9hl01yXsDGTqGeddSGvg7mrBS/wXHgENnzn9KMUJsbLxRaHgr85klTTqPaagq7q/Ayqpgc=,iv:sK4UhjhTJSfmkDPLyA6n8KpJSEnLQZCbeoUz5mlYVSw=,tag:29IVQScS+ML1z+x4cf8Wdg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
