apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:9NxKaUXtfyJO8vdDGiP7V3g7t0Uup66epA==,iv:2kwE0UrzUKUyVJ62ZD2ZTYq7Ec9hydb59yfvaDvh8Ds=,tag:kFaiJ6RJbTMepGh30pdPsg==,type:str]
    api-key: ENC[AES256_GCM,data:NYTDSIwWcjTdUS6PfEkwzjO+nWTcqp2c425TGa342nfV1pfcqg==,iv:PE+TeMRDnV/CM9fBm/X7cdT5Gki54c5qtwORgvNcbFI=,tag:SJAackM4p3YKw4Swfen7bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12npq05s3sct6q03znt84ppgdgpd7nwagsfkdvdxlu5e5dq5jn35smw5g3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRGVUSGJTYTZuRFo0YmVY
            QUorOWZ1SGJqdS9vUTNCS29VdkpkMkNsb0c4CktZbVlJcDRKelZ5dzFvWkNVcDRZ
            TnNPMGx6THZseGNPM3V0ejUzV2dYdXMKLS0tIHgvK0lsQWl1cktpRld2NUlabFFW
            NDV2b2dSUHFLaUYzR2d6WDF0ckh6bzAK2XLVMMgJpuVsh6Op+7C0R9ZWlqMPHy67
            PR+pMvUhE/0UormMUmIUP/kcbkh4WWLxbmQW66kg0mUIhNYGhd5jCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T08:15:41Z"
    mac: ENC[AES256_GCM,data:kXwdABZsBOGsDy2EiesOG81dlwku+HI218+TLiCD9j4M08CkT+u7xVUM7qw0j1jq5Hp8oz3V8vF9OGAMFeLbPS58y8D/0nZlWZZpkqy2iv3i4+2d1edNcigY2TrdJu+a5AV1qcH2AaqvCb1N0YUjCV1Yhi9N8/FgFX1kZVMzkm4=,iv:+tlsXhQ+Vtt6a7Un/hQqyEDWa9V3UwDqyxEmp8cZ3Q0=,tag:FXuy6eqr6JlYx+U7K+R0tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
