apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:nWgQ6h5I/20nQFvwAMfn65Z5qBz20HN2cT0UgkOjoF8b0A8o5AgEq2yFo6QkIf2ZhowI8eoM+KcPu75w,iv:nnWFtL56hYwZ9L9gKAJ62kZhUJ9uY/0viDNXjUnPZIM=,tag:0IpemwFhLjjVXz6cGT33mA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12npq05s3sct6q03znt84ppgdgpd7nwagsfkdvdxlu5e5dq5jn35smw5g3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArLysvelhWa3RKdmhqZC85
            RkpJdmVMYUlKUHZ0bzVIYXYvZFRlUFlIamlRCjlGQTBKSlIwbXFtYXJ5QkFEMHBG
            UU5WRXBSYmdEQTh1MkRxS3BaRTJOc0UKLS0tIGRGNkdvNk5wbCtVemRrVU1ZdEdl
            SnhkR1lCbGVBNEs4eGU3aXl6aS9weWMKLlP2G7uloTBN+3NrEjR2uqnB2mYndVUA
            2w4kTYzKZc6hjj02bU5SIw61aKA4fAAXwVGiInUcIPkpe0q2K8Py1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T08:15:41Z"
    mac: ENC[AES256_GCM,data:Ty4xCzq5WEIyRXobb/7LEJj1hCAYmQF0qoJ+WAmtgNqtDB7st1Gua1rONQzzVjcsx/HSUkul3sa0GOrbLIFaO10gfWVh5VAsQ+O5fqzlhmymfhBD3hadK2YmNHt7Nw5gnvY2euvVydyrcLPpACt0+hkRbsHy0CcTmRGCdnlYAUw=,iv:c/OagD4WvEWB+t06cyo6U5P+IG7ur4z1ucGoM3nKB8k=,tag:FM5DH6OLMYQYu3kJEZD5og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
