apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:f48JH42EaltQiMQ4MDc=,iv:wsY+01SigoPGcm24Od0P50b0nHWsQCWj59j6lZda+NQ=,tag:NENyycECsBS6t77Bp5FYow==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UbsFaDeQte/GeGyDEgbw9Ii5BUT7bA1prA==,iv:LBHi/YHp/sIci+xGCsGKLqvowSz1+UunIZxzio7Ti/M=,tag:wQ7TcPqgPkJt1m8N8kvzxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12npq05s3sct6q03znt84ppgdgpd7nwagsfkdvdxlu5e5dq5jn35smw5g3l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QkdxVk4xZG15dEc5TnJw
            RlNtN2krUEh6UTFoVHM0TTdYOG41MTRrWHlvCkM2bWp5ZHRldzhNSWZCaEJhU2FR
            WmZ3M0VzQ3JtTU8xQ1R5ckVEa3NFaEUKLS0tIFJWcWtuTEo4RGJRZEJMWitkQ3cx
            L1VIVzE2Y2l3K1BQVnYxWFlybmRpczAKD37MuIds5M9sYz9QViVCWqdw1J0cfDSq
            DoTrsMeWoPUwsX1OXjYYzckt4dydKcIaJoe+aesv5KrY4+rpafUf7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T09:37:55Z"
    mac: ENC[AES256_GCM,data:c1AFlxUVN0BfacZEh3c0djJ15rc1gfkDFss4QJi41QVNduX3kZHcqlAb/dEcL76T+w4iemX8m9+aNGnUlmATu3ABV08vel6N3B+YFeWCjzTMgoj1ejnjG/1wkT284LyeZ2ejNJsk12PtPqpYMhO8Z7ia2yH4AaTvoXtQ8ww1xf0=,iv:3yR/WCzfSfr0ahOOBY464+LQFLBRT3AsJYbfRCBGMFE=,tag:l6ypPyQaV3p8cvmTyZK8wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
