---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Oslo"
  KUBE_VIP_ADDR: "192.168.122.254"
  METALLB_LB_RANGE: "192.168.122.220-192.168.122.230"
  METALLB_K8S_GATEWAY_ADDR: "192.168.122.220"
  METALLB_INGRESS_ADDR: "192.168.122.221"
